services:
  watchdog:
    image: "elio11/ip-canary:latest"
    container_name: "ip-canary-watchdog"
    restart: unless-stopped
    environment:
      - MODE=watchdog
      - INSTANCE_NAME=ip-canary-watchdog # optional, defaults to container hostname if not set
      - CHECK_INTERVAL=60 # optional, default is 60 seconds
      - USE_GOTIFY=true # optional, default is true. Set to false to disable Gotify notifications.
      - MESSAGE_REPEAT_SECONDS=1800 # optional, default is 1800 seconds (30 minutes)
      # Either PUBLIC_IP or REAL_IP_URL, or both must be set.
      # - PUBLIC_IP=___
      - REAL_IP_URL=http://ip-canary-provider:9516/public-ip # This example URL works here because both services share the same Docker network. In a real deployment, point this to your ip_provider URL.
      - PROVIDER_FAILURE_TOLERANCE=3 # optional, default is 3 consecutive failures
      - GOTIFY_URL=--- # mandatory if USE_GOTIFY=true
      - GOTIFY_API_KEY=--- # mandatory if USE_GOTIFY=true
    volumes:
      - ./shared-state:/shared-state

  ip_provider:
    image: "elio11/ip-canary:latest"
    container_name: "ip-canary-provider"
    restart: unless-stopped
    environment:
      - MODE=ip_provider
    ports:
      - "9516:9516"

  heartbeat_observer:
    image: "elio11/ip-canary:latest"
    container_name: "ip-canary-observer"
    restart: unless-stopped
    volumes:
      - ./shared-state:/shared-state
    environment:
      - MODE=heartbeat_observer
      - INSTANCE_NAME=ip-canary-observer
      - CHECK_INTERVAL=60 # how often the observer checks observed state files
      - HEARTBEAT_STALE_SECONDS=360 # default is 360 seconds (6 minutes)
      - USE_GOTIFY=true
      - GOTIFY_URL=--- # mandatory if USE_GOTIFY=true
      - GOTIFY_API_KEY=--- # mandatory if USE_GOTIFY=true